/*
 * DCMotor_Program.c
 *
 *  Created on: Jul 9, 2023
 *      Author: DeLL
 */

#include "BIT_MATH.h"
#include "STD_TYPES.h"
#include "defines.h"
#include "util/delay.h"
#include "DIO_Interfce.h"

#include "StepperMotor_Cfg.h"
#include "StepperMotor_Private.h"
#include "StepperMotor_Interface.h"

void STEPPERMOTOR_voidInit(void)
{
	//Configure Direction of pins as O/P
	DIO_u8SetPortDerection(STEPPERMOTOR_u8PORT,DIO_u8PORT_OUTPUT);
	//Initialize their values with high == Stop
	DIO_u8SetPortValue(STEPPERMOTOR_u8PORT, DIO_u8PORT_HIGH);
}


void STEPPERMOTOR_voidRotateClockWise(void)
{

	/* Active blue  */
	DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_1,DIO_u8PIN_LOW);
	DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_2,DIO_u8PIN_HIGH);
	DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_3,DIO_u8PIN_HIGH);
	DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_4,DIO_u8PIN_HIGH);
	_delay_ms(2);

	/* Active pink  */
	DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_1,DIO_u8PIN_HIGH);
	DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_2,DIO_u8PIN_LOW);
	DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_3,DIO_u8PIN_HIGH);
	DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_4,DIO_u8PIN_HIGH);
	_delay_ms(2);


	/* Active yellow */
	DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_1,DIO_u8PIN_HIGH);
	DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_2,DIO_u8PIN_HIGH);
	DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_3,DIO_u8PIN_LOW);
	DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_4,DIO_u8PIN_HIGH);
	_delay_ms(2);


	/* Active orange  */
	DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_1,DIO_u8PIN_HIGH);
	DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_2,DIO_u8PIN_HIGH);
	DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_3,DIO_u8PIN_HIGH);
	DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_4,DIO_u8PIN_LOW);
	_delay_ms(2);

}
void STEPPERMOTOR_voidRotateCounterClockWise(void)
{

	/* Active blue  */
	DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_1,DIO_u8PIN_HIGH);
	DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_2,DIO_u8PIN_HIGH);
	DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_3,DIO_u8PIN_HIGH);
	DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_4,DIO_u8PIN_LOW);
	_delay_ms(2);

	/* Active pink  */
	DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_1,DIO_u8PIN_HIGH);
	DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_2,DIO_u8PIN_HIGH);
	DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_3,DIO_u8PIN_LOW);
	DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_4,DIO_u8PIN_HIGH);
	_delay_ms(2);


	/* Active yellow */
	DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_1,DIO_u8PIN_HIGH);
	DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_2,DIO_u8PIN_LOW);
	DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_3,DIO_u8PIN_HIGH);
	DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_4,DIO_u8PIN_HIGH);
	_delay_ms(2);


	/* Active orange  */
	DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_1,DIO_u8PIN_LOW);
	DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_2,DIO_u8PIN_HIGH);
	DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_3,DIO_u8PIN_HIGH);
	DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_4,DIO_u8PIN_HIGH);
	_delay_ms(2);

}
void STEPPERMOTOR_voidRotateWithAngle(uint8 Copy_u8Direction,uint8 Copy_u8Angle)
{
	uint16 Local_u16Stepper_Full_Step;
	uint16 Local_u16Counter_I;

	/*must do this casting  */
	Local_u16Stepper_Full_Step = (uint16)((uint32)Copy_u8Angle * 2048UL / 360UL );


	if( Copy_u8Direction == ROTATE_COUNTERCLOCKWISE  )
	{

		for(Local_u16Counter_I = 0 ; Local_u16Counter_I < Local_u16Stepper_Full_Step ;Local_u16Counter_I++)
		{
			if(Local_u16Counter_I % 4 == 0)
			{
				/* Active blue  */
				DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_1,DIO_u8PIN_HIGH);
				DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_2,DIO_u8PIN_HIGH);
				DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_3,DIO_u8PIN_HIGH);
				DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_4,DIO_u8PIN_LOW);
				_delay_ms(2);
			}else if (Local_u16Counter_I % 4 == 1)
			{
				/* Active pink  */
				DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_1,DIO_u8PIN_HIGH);
				DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_2,DIO_u8PIN_HIGH);
				DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_3,DIO_u8PIN_LOW);
				DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_4,DIO_u8PIN_HIGH);
				_delay_ms(2);
			}else if (Local_u16Counter_I % 4 == 2)
			{

				/* Active yellow */
				DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_1,DIO_u8PIN_HIGH);
				DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_2,DIO_u8PIN_LOW);
				DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_3,DIO_u8PIN_HIGH);
				DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_4,DIO_u8PIN_HIGH);
				_delay_ms(2);
			}else if (Local_u16Counter_I % 4 == 3)
			{
				/* Active orange  */
				DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_1,DIO_u8PIN_LOW);
				DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_2,DIO_u8PIN_HIGH);
				DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_3,DIO_u8PIN_HIGH);
				DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_4,DIO_u8PIN_HIGH);
				_delay_ms(2);
			}

		}

	}else if (Copy_u8Direction == ROTATE_CLOCKWISE)
	{
		for(Local_u16Counter_I = 0 ; Local_u16Counter_I < Local_u16Stepper_Full_Step ;Local_u16Counter_I++)
		{
			if(Local_u16Counter_I % 4 == 0)
			{

				/* Active blue  */
				DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_1,DIO_u8PIN_LOW);
				DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_2,DIO_u8PIN_HIGH);
				DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_3,DIO_u8PIN_HIGH);
				DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_4,DIO_u8PIN_HIGH);
				_delay_ms(2);
			}else if (Local_u16Counter_I % 4 == 1)
			{
				/* Active pink  */
				DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_1,DIO_u8PIN_HIGH);
				DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_2,DIO_u8PIN_LOW);
				DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_3,DIO_u8PIN_HIGH);
				DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_4,DIO_u8PIN_HIGH);
				_delay_ms(2);


			}else if (Local_u16Counter_I % 4 == 2)
			{
				/* Active yellow */
				DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_1,DIO_u8PIN_HIGH);
				DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_2,DIO_u8PIN_HIGH);
				DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_3,DIO_u8PIN_LOW);
				DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_4,DIO_u8PIN_HIGH);
				_delay_ms(2);

			}else if (Local_u16Counter_I % 4 == 3)
			{
				/* Active orange  */
				DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_1,DIO_u8PIN_HIGH);
				DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_2,DIO_u8PIN_HIGH);
				DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_3,DIO_u8PIN_HIGH);
				DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_4,DIO_u8PIN_LOW);
				_delay_ms(2);
			}
		}

	}

}


void STEPPERMOTOR_voidStop(void)
{
	DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_1,DIO_u8PIN_HIGH);
	DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_2,DIO_u8PIN_HIGH);
	DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_3,DIO_u8PIN_HIGH);
	DIO_u8SetPinValue(STEPPERMOTOR_u8PORT,STEPPERMOTOR_u8ULN2003_BASE_4,DIO_u8PIN_HIGH);
	_delay_ms(2);
}
